

CREATE TABLE BLOG(
    ID VARCHAR(36) PRIMARY KEY,
    TITLE VARCHAR(256) NOT NULL,
    BODY TEXT NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    IMG VARCHAR(256) NOT NULL,
    CREATED_AT DATE NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (CREATED_BY) REFERENCES USER(EMAIL)
);

CREATE TABLE LIKES(
    BLOG_ID VARCHAR(36) NOT NULL,
    LIKED_BY VARCHAR(100) NOT NULL,
    FOREIGN KEY (BLOG_ID) REFERENCES BLOG(ID),
    FOREIGN KEY (LIKED_BY) REFERENCES USER(EMAIL),
    UNIQUE (BLOG_ID,LIKED_BY) 
);