CREATE TABLE USER(
NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) PRIMARY KEY,
PROFILE_PIC TEXT NOT NULL,
  ABOUT TEXT
);


CREATE TABLE SOCIAL_LINKS(
  USER_EMAIL VARCHAR(100)  NOT NULL ,
  LINK VARCHAR(256) NOT NULL,
  FOREIGN KEY (USER_EMAIL) REFERENCES USER(EMAIL),
  UNIQUE(USER_EMAIL,LINK)
);


CREATE VIEW USER_PROFILE 
    AS SELECT U.NAME  AS 'NAME'
    ,U.EMAIL AS 'EMAIL'
    ,U.PROFILE_PIC AS 'PROFILE_PIC'
    ,U.ABOUT AS 'ABOUT'
    ,GROUP_CONCAT(L.LINK) AS 'LINKS'
    FROM USER U LEFT JOIN SOCIAL_LINKS L 
    ON U.EMAIL = L.USER_EMAIL GROUP BY U.EMAIL;